---
output: pdf_document
bibliography: trust_stability-prominent-works.bib
nocite: '@*'
---

```{=tex}
\pagenumbering{arabic}
\setcounter{page}{1}
\renewcommand*{\thepage}{\arabic{page}}
```

# Political Discontent as DV

How to explain these disparities in public political discontents across countries? What are the drivers of the changes over years? The literature presents various perspectives on how political and economic contexts may affect public political discontent. The first argument deals with the role of election. Elections provide an opportunity for people to turning their dissatisfaction into ballots for candidates or parties that promise changes to the system. Discontented citizens, as a result, gain political fulfillment through voting for a party voicing their discontents [@van2003lpf; @rooduijn2016expressing]. From this perspective, public political discontent should be expected to be lower in years of national elections, where some of the existing discontents could be ameliorated. However, existing studies also suggest that the effect of election time on public political discontent could be the opposite. During election times, citizens are exposed to more political messages, a significant proportion of which are those criticizing the elites and the system [@lau2007effects; @lopez2019political]. Particularly, many advanced democracies are experiencing increased levels of false information during elections, which has become a clear danger to the integrity of political process [@bennett2018disinformation]. If so, public political discontent may be expected to be higher at election times.


The second potential source of public political discontent is the distribution of power created by political institutions. According to prominent democratic theories [@norris2008driving; @lijphart1999patterns; @powell2000elections], power-sharing systems—parliamentarism, federalism, and proportional electoral rules—aim to generate governments that facilitate broad inclusion and participation, while power-concentrating systems prioritize to generate efficient and accountable majority rule. @kittilson2010engaging argue, power-sharing systems, not only encourage actual political participation, but also send symbolic signals of inclusiveness to citizens. If so, the publics in countries with parliamentary, federal systems, and proportional electoral rules should be more likely to perceive themselves as being included and represented in the system, thereby being less discontented.

The third focus is political corruption. A number of studies have shown that people’s experience with and perception of corruption yield salient negative impacts on the perceived institutional performance and responsiveness of the political system [@della2000social; @uslaner2017political; @busby2018activating; @hawkins2020activation]. If so, public political discontents should be higher in countries where corruption is pervasive, which problem drives people perceive political authorities working for their own interests without addressing public demands.

Lastly, economic conditions, particularly inequalities, are argued to be salient sources of political discontent [@quaranta2016does]. For one thing, unfavorable economic conditions fuel social discontent and anxiety about the future among the public, which can easily evolve into anti-establishment sentiments [@kinnvall2022exploring]. For another, economic indicators are usually used by people to evaluate the performance of the system or government policies [@becher2013economic]. Hence, poor economic conditions, such as slow growth, high unemployment, and significant disparity, are likely to hurt the perceived institutional quality, thus increasing public political discontent.

# Bibliography
