---
output: pdf_document
bibliography: trust_stability-prominent-works.bib
nocite: '@*'
---

```{=tex}
\pagenumbering{arabic}
\setcounter{page}{4}
\renewcommand*{\thepage}{A\arabic{page}}
```

# Prominent Works
## 1) Theoretical Works
- @VanderMeer2017 has a good discussion of the conceptulization of "political trust", such as the subjects of political trust, and its distinction with related concepts, such as "political support", skepticism, etc.
- @Almond1963 argue that the sense of trust in the political elite makes citizens willing to turn power over to them, and, the maintenance of elite power is essential in a democracy.
- @hetherington1998political provides a comprehensive overview of the debates surrounding the political relevance of political trust. One classic approach views political trust as stemming from the assessment of incumbents and institutions, akin to specific support, and posits limited political relevance toward the regime. In contrast, the other classic approach regards political trust as akin to diffuse support. Therefore, while political trust may be influenced by the evaluation of regime performance, it can also significantly contribute to negative evaluations of the regime.Two mechanisms were discussed in this context:1) Diminishing trust in political institutions calls into question the legitimacy of democracy, which is founded on these institutions. 2) Distrust leads to disapproval, which in turn hinders leaders' ability to mobilize resources to address issues, resulting in fewer problems being solved. Consequently, distrust creates conditions conducive to further distrust.
- @martin2010does provides a good summary of old debate over the political relevance of political trust. Arthur Miller (1974), Stokes (1962), and Almond and Verba (1963) proposed that the public's sentiments toward government, including political trust, play a crucial role in the stability of the regime overall. However, Citrin (1974) presents a contrasting viewpoint, arguing that low political trust primarily stems from dissatisfaction with incumbents and does not significantly impact diffuse support for democracy.
- @dawson2024political provides a good summary of the critical citizen thesis that comparatively lower levels of political trust is not a threat to democracy but a sign of a health democracy. While “critical” or “assertive” citizens exercising their democratic right to publicly criticize and challenge political institutions may decrease trust in those institutions, these challenges are thought to be an important aspect of – and therefore not threaten – the democratic political system. So, low political trust is not a threat to the regime.
- @mishler2005political suggests three mechanism in detail that how low institutional trust can threten the stability of democracy. 1) Institutional trust increases diffuse support for democracy or public support for democratic regime, 2) Higher institutional trust facilitates the public’s acceptance of democratic values and ideals and its rejection of undemocratic alternatives and 3) Higher institutional trust promotes both the quality and quantity of political involvement. 
- @kwak2020youth argues that the difference between young people and old people's political trust is relevant for political changes because governing elites respond to the political values and attitudes of the both following the logic of generational succession. Therefore, the values and attitudes of the young are not crucial per se, but in how they relate to the values and attitudes of the older cohorts.
- @van2017deeply provides a solid conceptualization of political trust that it is fundamentally relational and situational. "It is relational because it has a subject who trusts and an object that is trusted; we do not argue that person A trusts without reference to a trust object. Trust is situational since it is commonly given or withheld with reference to specific types of actions or environments. Trust is therefore expressed as ‘A trusts B to do X’ (Hardin, 2000, p. 26) or as ‘a state of mind for individuals, but. . .also a characteristic of a polity’ (Dalton, 2004, p. 162). Trust relationships are defined by the subject’s degree of uncertainty or vulnerability regarding the object’s future behaviour (Newton, 1999, p. 170; Van der Meer, 2016)." Furthermore, it provides a good general overview of the development of literature about political trust in many aspects. Lastly, this paper says "systematic research on the consequences of political trust has remained remarkably scarce, as many scholars have acknowledged in recent years." and summarize a few recent findings (pg.8).


## 2) Empirical Works
- @Marien2011 examine the relation between trust in the institutions of the political system and law-abiding attitudes using the 1999–2001 European Values Study. In this study, "political trust" is operationalized as an index summing up trust in parliament, in the justice system, in the armed forces, and in the police. They find citizens with low levels of trust feel it more acceptable to break the law, such as commit tax fraud.
- @Dalton2004 reports that there is a rising trend of political distrust in advanced industrial democracies, which may erode the vitality of democracy and bring political change. Citizens who do not trust government and institutions appear to be less willing to comply with the law and the directives of government. Distrustful citizens also appear to be less involved in the traditional channels of representative democracy, such as voting and campaign activity, but are more likely to seek influence through protest and other direct forms of action.
- @hetherington2005trust explores the consequences political trust on policy level, using the case of public support for redistributive programs in the U.S. He finds that, as political trust declines, citizens tend to prefer smaller government, even though their values do not become less liberal. In a later study, @hetherington2012trust show the effect of political trusts dependent on political issue's salience and media coverage.
- @hetherington1998political used Structural Equation Modeling with 1988 and 1996 NES, and political trust is measured by asking four questions about one's trust in the government in Washington. The result demonstrates that political trust is related to the diffuse and specific support. Specifically, trust's effect on feelings about the incumbent president, a measure of specific support, is even stronger than the reverse. However, it is not the case for feelings about Congress
- @martin2010does utilizes data from the 2007 Australian Election Study (AES) to investigate political trust, measured through a question regarding trust in government. Employing Ordinary Least Squares (OLS) analysis, the findings indicate that greater trust in government correlates with more favorable attitudes toward democracy, although it does not impact anti-democratic sentiments. Furthermore, higher levels of trust are associated with an increased voting intention.
- @dawson2024political empirically tests the critical citizen thesis by using WVS and EVS from 1981 to 2020. Political trust is measured by one's trust in six political institutions – the civil service, police, justice system/courts, parliament, government and political parties. The results provides a support for the critical citizens thesis that the level of democracy is negatively related to political trust.
- @mishler2005political measures institutional trust by combining one's trust in the following institutions: “political parties,” “the president of Russia,” “the governor of this region,” “Duma members,” “the Duma representative of the single member district in which you live,” “the Constitutional Court,” “the police,” “the Army,” and “the Federal Security Service.” The dataset is New Russia Barometer survey conducted in 2001 in Russia. By using the Structural Equation Modeling, the results show that trust in political institutions encourages citizen involvement in politics and enhances support for democratic ideals, but it does not influence citizens’ support for the current regime or for plausible undemocratic alternatives. On the other hand, institutional trust and support for the new regime are both products of a common underlying dynamic—citizen assessments of political institutions' work in reducing corruption and providing reasonable economic stability and growth.
- @kwak2020youth uses an data set that combines a country-year indicator of liberal democracy and aggregate measures of absolute and relative trust of the young in political institutions for more than 45 countries from 2009 to 2017. Political trust is measured by one's trust in parliament, legal system, and political parties. The result shows that the absolute measure of youth trust in political institutions has a noticeable effect on liberal democracy, meaning the lower trust in political institutions among young people, the larger the decrease in level of democracy Y in the future. Also, the relative measure of youth institutional trust has a substantial effect on changes in liberal democracy. The results from OLS regression analyses showed that the lower trust ratios of young people to older people in political institutions except legal system, the larger the decline in level of democracy in the future.
- @ruck2020cultural stands out for its extensive sample coverage, possibly the widest seen to date, although the methodology explanation remains somewhat limited. Institutional trust is assessed by measuring confidence levels in various entities including parliament, government, civil service, police, labor unions, major companies, the press, and the armed forces. Findings indicate that a previous change in democracy weakly predicts a subsequent increase in institutional confidence. However, this effect is less substantial and inconsistent compared to the effect running in the opposite direction. Put simply, the results suggest that prior changes in institutional trust have a stronger and more consistent impact on democracy than the reverse.

# Bibliography
